### ISSUE TITLE
getEditFormEditor: object expected (v15.2)

### ISSUE THREAD

**Issue by OJuretzki** [DevExpress/TestCafe-Wrappers#1]
Function getEditFormEditor does not work. dx.edit is undefined. Is the parameter createWrapperMethod documented somewhere?

`
  var getEditFormEditor = function(indexOrCaption, createWrapperMethod){
        var index = indexOrCaption;
        if(typeof index == "string")
            index = findColumnIndex(indexOrCaption);
        if(!createWrapperMethod)
            createWrapperMethod = dx.edit;
        return createWrapperMethod("DXEditor" + index);
    };
`

**Comment by MarinaRukavitsyna** [comment]
Please clarify whether you are using old tests with new wrappers or create new ones.

**Comment by OJuretzki** [comment]
Hi Marina,

i created a new fixture to test the new wrappers.

**Comment by MarinaRukavitsyna** [comment]
To work with the getEditFormEditor method, your need to use editor wrappers that we do not currently provide. Please open a thread at https://www.devexpress.com/Support/Center/Question/Create, so that I can provide you with scripts that may be helpful in your scenario.
